[mypy]
python_version = 3.12
files = logic, ui, tests, main.py
exclude = (^build/|^dist/|^backups/|^\.venv/)
show_error_codes = True
pretty = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_return_any = True

[mypy-pytest]
ignore_missing_imports = True

[mypy-customtkinter]
ignore_missing_imports = True

[mypy-tkcalendar]
ignore_missing_imports = True

[mypy-PIL]
ignore_missing_imports = True

[mypy-bcrypt]
ignore_missing_imports = True

[mypy-openpyxl]
ignore_missing_imports = True

[mypy-openpyxl.*]
ignore_missing_imports = True

[mypy-win32api]
ignore_missing_imports = True

[mypy-win32print]
ignore_missing_imports = True
